$.socialfloating({
	icons:"semanticui",
	buttons:
	[
		{icon:"facebook",enabled:!0,link:"https://www.facebook.com/jqueryscript/",color:"#3b5998"},
		{icon:"twitter",enabled:!0,link:"https://twitter.com/jqueryscript",color:"#00aced"},
		{icon:"github",enabled:!0,link:"https://www.github.com/jqueryscript",color:"#333333"}
	]
});
